export const CREATE_STUDENT = "CREATE_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const FILTER_STUDENT_BY_GENDER = "FILTER_STUDENT_BY_GENDER";
export const SHORT_STUDENT_BY_DOB = "SHORT_STUDENT_BY_DOB";
export const DELETE_STUDENT = "DELETE_STUDENT";
